version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-template}
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-mydb}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-dbuser}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-password123}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DB_DDL_AUTO:-update}
      JAVA_OPTS: ${JAVA_OPTS:--Xms256m -Xmx512m -XX:+UseG1GC}
      TZ: ${TZ:-Europe/Lisbon}
      LOGGING_COLORS_ENABLED: ${LOGGING_COLORS_ENABLED:-false}
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: ${DB_CONTAINER:-postgres-db}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-mydb}
      POSTGRES_USER: ${DB_USER:-dbuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      TZ: ${TZ:-Europe/Lisbon}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
