
logging:
  colors:
    enabled: ${LOGGING_COLORS_ENABLED:false}

spring:
  application:
    name: template
  ### Database log Configuration ###
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  ### H2 Database ###
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver