
spring:
  application:
    name: template

### H2 Database Configuration ###
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true